/**
* Vanshita Garg | 19CS10064
* Ashutosh Kumar Singh | 19CS30008
* Compilers Laboratory
* Assignment 6
*
* Header file for translation
*/

#ifndef __TRANSLATOR_H
#define __TRANSLATOR_H

#include <iostream>
#include <vector>
#include <list>
#include <map>
using namespace std;


/*
    An enum for all data dtype
*/
typedef enum {
    VOID,
    BOOL,
    CHAR,
    INT,
    FLOAT,
    ARRAY,
    POINTER,
    FUNCTION
} data_dtype;

/*
    An enum for all opcodes
*/
typedef enum  {
    ADD, SUB, MULT, DIV, MOD, SL, SR, 
    BW_AND, BW_OR, BW_XOR, 
    BW_U_NOT ,U_PLUS, U_MINUS, REFERENCE, DEREFERENCE, U_NEG, 
    GOTO_EQ, GOTO_NEQ, GOTO_GT, GOTO_GTE, GOTO_LT, GOTO_LTE, IF_GOTO, IF_FALSE_GOTO, 
    CtoI, ItoC, FtoI, ItoF, FtoC ,CtoF, 
    ASSIGN, GOTO, RETURN, PARAM, CALL, ARR_R, ARR_L, FUNC_BEG, FUNC_END, L_DEREF
} opcode;


/*
    Forward Class Declarations
    --------------------------
    ST_entry          Represents an element(entry) in the ST_entry table
    ST_entry_type      Represents the type of an element in the ST_entry table
    ST_entryValue     Represents the value stored by a ST_entry in the ST_entry table
    symbol_table     Represents the ST_entry table data structure itself
    quad            Denotes a quad in the Three Address Code translation
    quad_TAC_arr       Denotes the entire list of quads for lazy spitting
*/
class ST_entry;
class ST_entry_type;
class ST_entryValue;
class symbol_table;

class quad;
class quad_TAC_arr;


/*
    External variables and methods generated by bison
*/
extern char* yytext;
extern int yyparse();


/*
    Class to represent the type of an element in the ST_entry table
    class ST_entry_type
    ----------------
    Member Variables:
        pointers: int               Useful for pointer dtype
        type: data_dtype              The type of the ST_entry
        next_elem_type: ST_entry_type        For arrays and pointers, it points to the type of the elements of the array or the pointer
        dims: vector<int>           For arrays, it stores the dimensions of the array
*/
class ST_entry_type {
public:
    int pointers;
    data_dtype type;
    data_dtype next_elem_type;
    vector<int> dims;
};


/*
    Class to represent the value of an element in the ST_entry table
    class ST_entryValue
    ------------------
    Member Variables:
        i: int                 For integers, it stores the value
        f: float               For floats, it stores the value
        c: char                For characters, it stores the value
        p: void*               For pointers, it stores the value
*/
class ST_entryValue {
public:
    int i;
    char c;
    float f;
    void* p;

    void initialize(int val);
    void initialize(char val);
    void initialize(float val);
};


/*
    Class to represent an element(entry) in the ST_entry table
    class ST_entry
    ------------
    Member Variables:
        name: string                The name of the ST_entry
        type: ST_entry_type            Type of the ST_entry
        initial_value: ST_entryValue*       Initial value of the ST_entry, if any
        size: int                   Size of the ST_entry(element)
        offset: int                 Offset of the ST_entry in the ST_entry table
        nested_symbol_table: symbol_table*   Pointer to a nested ST_entry table, if any (useful for functions and blocationks)
    Member Methods:
        ST_entry()
        - Constructor
*/
class ST_entry {
public:
    string name;
    ST_entry_type type;
    ST_entryValue* initial_value;
    int size;
    int offset;
    symbol_table* nested_symbol_table;

    ST_entry();
};


/*
    Class to represent the ST_entry table data structure
    class symbol_table
    ------------
    Member Variables:
        table: map<string, ST_entry*>     List of ST_entrys hashed using their names
        ST_entrys: vector<ST_entry*>        List of all ST_entrys present in the ST_entry table
        tempCount: int                  Count of temporary variables generated for the ST_entry table
        parent: symbol_table*            Pointer to the parent of the ST_entry table, NULL for the global ST_entry table
    Member Methods:
        symbol_table()
        - Constructor
        search_lexeme(string name, data_dtype t = INT, int pc = 0): ST_entry*
        - A method to search_lexeme an id (given its name or lexeme) in the ST_entry table. If the id exists, the entry is returned, otherwise a new entry is created.
        searchGlobal(string name): ST_entry*
        - A method to search for an id in the global ST_entry table. If the id exists, the entry is returned, otherwise NULL is returned.
        generate_tem_var(data_dtype t = INT): string
        - A method to generate a new temporary, insert it to the ST_entry table, and return a pointer to the entry
        print(): void
        - Prints the ST_entry table in a suitable fashion
*/
class symbol_table {
public:
    map<string, ST_entry*> table;
    vector<ST_entry*> ST_entrys;
    int offset;
    static int tempCount;

    symbol_table();
    ST_entry* search_lexeme(string name, data_dtype t = INT, int pc = 0);
    ST_entry* searchGlobal(string name);
    string generate_tem_var(data_dtype t = INT);

    void print(string tableName);
};


/*
    Class to denote a quad in the Three Address Code translation
    class quad
    ------------
    Member Variables:
        op: string          Operator in the three address code
        arg1: string        First argument in the three address code
        arg2: string        Second argument in the three address code
        result: string      Result of the three address code
    Member Methods:
    quad(string, string, string, opcode)
    - Constructor
    print(): void
    - Returns a formatted string to help in printing the quad
*/
class quad {
public:
    opcode op;
    string arg1;
    string arg2;
    string result;

    quad(string, string, string, opcode);

    string print();
};


/*
    Class to denote the entire list of quads for lazy spitting
    class quad_TAC_arr
    ------------
    Member Variables:
        quads: vector<quads>    A vector of all the quads generated
    Member Methods:
        print(): void
        - Prints the entire list of quads
*/
class quad_TAC_arr {
public:
    vector<quad> quads;

    void print();
};


/*
    Class to represent a parameter
    class param
    ------------
    Member Variables:
        name: string        Name of the parameter
        type: data_dtype      Type of the parameter
*/
class param {
public:
    string name;
    ST_entry_type type;
};


/*
    Class to denote an expression
    class expression
    ------------
    Member Variables:
        instr: int                  The instruction number of the expression
        type: data_dtype              Type of the expression
        location: string                 The ST_entry table entry 
        truelist: list<int>         Truelist for boolean expressions
        falselist: list<int>        Falselist for boolean expressions
        nextlist: list<int>         Nextlist for statement expressions
        fold: int                   Useful for arrays and pointers
        folder: string*             Useful for arrays and pointers
    Member Methods:
        expression()
        - Constructor
*/
class expression {
public:
    int instr;
    data_dtype type;
    string location;
    list<int> truelist;
    list<int> falselist;
    list<int> nextlist;
    int fold;
    string* folder;

    expression();
};


/*
    Class to represent a declaration
    class declaration
    ------------
    Member Variables:
        name: string                Name of the declaration
        pointers: int               Number of pointers
        type: data_dtype              Type of the declaration
        li: vector<int>             List of instructions for the declaration
        initial_value: expression*        Initial value of the declaration
        pc: int                     Useful for pointers and arrays
*/
class declaration {
public:
    string name;
    int pointers;
    data_dtype type;
    data_dtype next_elem_type;
    vector<int> li;
    expression* initial_value;
    int pc;
};


/*
    An overloaded method to add a (newly generated) quad of the form: result = arg1 op arg2 where op usually is a binary operator. 
    If arg2 is missing, op is unary. If op also is missing, this is a copy instruction.
    It is overloaded for different dtype of quads (int, float or string)
*/
void add_TAC(string result, string arg1, string arg2, opcode op);
void add_TAC(string result, int constant, opcode op);
void add_TAC(string result, char constant, opcode op);
void add_TAC(string result, float constant, opcode op);


/*
    A global function to create a new list containing only i, an index into the array of quads, 
    and to return a pointer to the newly created list
*/
list<int> makelist(int i);

/*
    A global function to concatenate two lists list1 and list2 and to return a pointer to the concatenated list
*/
list<int> merge(list<int> list1, list<int> list2);

/*
    A global function to insert address as the target label for each of the quads on the list l
*/
void backpatch(list<int> l, int address);

/*
    Converts a ST_entry of one type to another and returns a pointer to the converted ST_entry
*/
void convertToType(expression* arg, expression* res, data_dtype toType);

void convertToType(string t, data_dtype to, string f, data_dtype from);

/*
    Converts an int to a bool and adds required attributes
*/
void convertIntToBool(expression* expr);

/*
    Auxiliary function to get the size of a type
*/
int sizeOfType(data_dtype t);

/*
    Auxiliary function to print a type
*/
string checkType(ST_entry_type t);

/*
    Auxiliary function to get the initial value of a ST_entry
*/
string getInitVal(ST_entry* sym);

#endif